name: HackUPC recruiting page CI

defaults:
  run:
    working-directory: .

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  DEBUG: 1
  IMAGE_TAG: ${{ github.job }}-${{ github.sha }}

jobs:
  lint:
    name: 🦄 Linter
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v5

      - name: 🏗 Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 18.x

      - name: 📦 Install dependencies
        run: npm install

      - name: 🦄 Check format (prettier)
        run: npm run check-format

      - name: 🦄 Check lint (eslint)
        run: npm run check-lint

  build:
    name: 🏗 Builder
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v5

      - name: 🏗 Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20.x

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗 Build
        run: npm run build
